"""initial schema

Revision ID: b545ad3baa0e
Revises: 
Create Date: 2026-07-10 00:52:09.450683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b545ad3baa0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botsetting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_horizon_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_target', sa.Float(), nullable=True),
    sa.Column('price_at_signal', sa.Float(), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('price_at_evaluation', sa.Float(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_evaluation_date'), 'signal', ['evaluation_date'], unique=False)
    op.create_index(op.f('ix_signal_ticker'), 'signal', ['ticker'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_ticker'), 'transaction', ['ticker'], unique=False)
    op.create_table('watchlistticker',
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlistticker')
    op.drop_index(op.f('ix_transaction_ticker'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_signal_ticker'), table_name='signal')
    op.drop_index(op.f('ix_signal_evaluation_date'), table_name='signal')
    op.drop_table('signal')
    op.drop_table('botsetting')
    # ### end Alembic commands ###
